import React from 'react'

export const privacy = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
 <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
    <p className="text-sm">Last Updated: February 2, 2022</p>
    <p className="mb-4 mt-5">
        This privacy policy (the "Privacy Policy") explains how Filipino Art ("FA," "we," or "us") collects, uses, shares, and protects information of the users of the filipinoart.ph website (the "Website"). This Privacy Policy is designed to fulfill our legal obligations in the places where we operate—including, without limitation and where applicable, Data Privacy Act in the Philippines (Republic Act No. 10173), the California Consumer Privacy Act (CCPA), and the General Data Protection Regulation (GDPR).
    </p>
    <p className="mb-4">
        Please note that this Privacy Policy only applies to the Website, and not to websites, applications, operating systems, or other platforms of third parties (collectively, "Third-Party Platforms"), even if such Third-Party Platforms are linked to or accessible from the Website. Each Third-Party Platform will have its own data collection and usage practices, and may use their own cookies, web beacons, and other technology to collect information from you. FA is not responsible for the content or practices of any Third-Party Platforms and, if you choose to visit or use them, you do so at your own risk.
    </p>
 <h3 className="text-2xl font-bold mb-2 mt-2">1.Who controls your information?</h3>
 <p>Any information or other data provided to or gathered by FA is controlled by Chanz IT Business Solutions Inc. Unit 1005 Centerpoint Building, Julia Vargas cor. Garnet Rd, 1605 Pasig City, NCR, Philippines</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">2. What types of information do we collect?
</h3>
 <p>"Information," as used in this Privacy Policy, means personal information that identifies, relates to, describes, is reasonably capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular user or household. Examples include a user's name, mailing address, email address, or IP address. FA collects and/or has collected over the past twelve (12) months the following categories of information about you and other users of the Website:
    Information You Provide to Us. We collect information from you when you voluntarily provide it to us over the Website, including as part of registering a user or ordering goods or services from FA. Such information may include, but is not limited to, your name, email address, telephone number(s), website URLs, your instant messaging screen names, your date of birth, street address, city, and/or state.
    Content You Make Public. The Website contains features that allow you to upload, post, transmit, display, perform or distribute content, including personal information about yourself. For example, you may choose to include personal information within your FA profile, which is available and accessible to all visitors of the Website. Any information that you choose to disclose by means of such features becomes public information over which FA is unable to exercise control. You should exercise caution when deciding to disclose personal information by means of such features.
    Device/Internet Connection Information. When you use the Website, we automatically gather information made available by your web browser (such as Microsoft Edge or Google Chrome), internet service provider (such as Comcast or Cox), and device (such as your computer, phone, tablet, or fitness tracker), depending on your settings for each. For example, we may collect your IP address, information about the operating system or type of device you use, the device ID associated with your device, the date and time you access the Website, and your log in attempts.
    Internet Activity Information. As explained below in Sections 3 and 4 regarding Personalized Ads, we may also collect information about your browsing history, search history, and information regarding your interaction the Website. We may collect information regarding the websites, application, or advertisement you visited immediately before and after your use of the Website.
    Geolocation Information. We may collect information about where you are located, both generally and at the time you access the Website. For example, we may collect your billing address when you make a purchase, or ascertain your approximate location from your IP address.
    Protected className Information. Due to the specific nature of FA' services, you may be asked for your age or be given the option to provide information about your gender.
    Other Information. From time to time, we may collect other information from you, such as when you make a claim for a prize pursuant to a contest or other promotion run on the Website, when you request assistance through our customer service department, or when you voluntarily subscribe to promotions, reminders, or newsletters. You will always be asked for your consent in advance of providing such other information, and we will not collect it without your permission.</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">3. How and when do we collect information about you?</h3>
 <p>FA gathers information about you through the following sources and means:
    When you enter or upload information to the Website. FA collects information you provide to us, content you make public, transaction and payment information, geolocation information, and protected className information when you enter such information on a form on the Website (including during registration), purchase services, sign up for newsletters or promotional material, enter contests, upload content, post in a forum, and otherwise interact with the Website.
    When you communicate with us. FA may also collect information you provide to us, content you make public, transaction and payment information, geolocation information, and protected className information, from you outside of the Website, such as when you contact our customer service department, email us (including any response to an email communication from FA), or communicate with FA via social media, such as by posting on a page hosted by FA or tagging FA in your own post. The information collected off the Website may be combined with that collected through the Website—for example, if you order a service from the Website and later call customer service about the order, the information collected in both interactions may be linked.
    Through Cookies, tracking tools, and other automated technologies. When you use any website, certain information can be automatically collected through technological means. When you access the Website, your web browser automatically sends us device and internet connection information and certain internet activity information as described in Section 2. FA also uses Cookies and web beacon technology to gather device and internet connection information, internet activity information, geolocation information, and biometric information. "Cookies" are files that are placed on your computer or other device by websites you visit. The primary purpose of a Cookie is to identify you as a unique user of the Website. FA uses the following types of Cookies, some of which are placed by Third Parties, to customize your Internet experience, keep you logged into websites, remember your search terms, and advertise products or services to you:AdvertisingWe may also use Cookies and web beacons, including those placed by Third Parties such as Google, to deliver Personalized Ads that may be of interest to you. We may also use a web beacon in email messages sent to track your response. Cookies and web beacons also help us and our Third-Party advertising partners ensure you do not see the same advertisements over and over.
    Type of Cookie	Purpose of Cookie
    Necessary	Necessary Cookies are essential in order for the Website to display and perform properly. Necessary Cookies are used to identify you, prevent security risks, and to allow you to perform -related functions.
    Preferences	Preferences Cookies are used to store preferences set by you and each user for their account, such as your language preferences. Preferences Cookies improve your experience using the Website.
    Analytics and Performance	Analytics and Performance Cookies collect information on how you and other users interact with the Website. Often, this information is aggregated, as discussed in Section 4, and is used to improve the Website.
    You can change your Cookie settings in your Internet browser (e.g., Chrome, Edge, Firefox). If you disable Cookies, some of the features of the Website may not function correctly. For more information, see allaboutcookies.org.
    From Third Parties. FA may also collect the following types of information from Third Parties: transaction and payment information (such as when you have your payment information saved in your web browser); device/internet connection information; internet activity information; geolocation information; analytics information; and biometric information. Like many websites, FA uses Google services and Cookies to improve the Website and advertise to users like you, as described more fully below. As such, when you use the Website, your personal information may be shared with Google, and shared by Google with FA. You can learn more about how Google uses Cookies, and how to manage your Cookie preferences in your Internet browser and revoke your consent to Personalized Ads, by visiting the Google Cookie Policy. Pixels, tags, and Cookies may also be set by our Third Party advertising partners, which may track your online behavior, track ads shown to you, and provide Personalized Ads to you. Statistical identification or other non-cookie technologies may be used by third parties, and browser settings that block cookies may have no effect on such technologies. Data collected by third parties from a particular browser or device may be used with another computer or device that is linked to the browser or device on which such data was collected. Because advertising revenue is the sole source of monetization for the free services provided by FA to you and other users of the Website, FA considers these to be essential services.</p>
    <h3 className="text-2xl font-bold mb-2 mt-2">4. How do we use your information?</h3>
 <p>FA may use the information we've gathered from you or your device, including through Cookies and Third Parties, for the following purposes:
    Business Purposes. When FA uses your information for a "Business Purpose," it means such use is reasonably necessary and proportionate to achieve an operational purpose of the FA. The following are the Business Purposes for which we may use your information:
    Business Purpose	Types of Information
    For Security. FA uses the information we collect from you and other users to detect security incidents, protect against malicious, deceptive, fraudulent, or illegal activity, and to identify and prosecute those responsible for that activity. For example, we look at IP addresses to determine if they are on the "ban list" for a given forum, so that we can prevent access to the forum.	Information you provide to us; Transaction and Payment Information; Device/Internet Connection Information; Internet Activity Information; Geolocation Information
    To Improve the Website. FA uses the information we collect from you and other users to provide and improve the Website. We use information to debug and identify and repair errors that impair existing intended functionality of the Website. As explained above, we use Cookies, including those placed by Third Parties, to gather statistical information that helps us understand how you and other users engage with the Website and improve its performance via technological development.	Information you provide to us; Content you make public; Device/Internet Connection Information; Internet Activity Information; Geolocation Information;
    To Personalize Your User Experience. We use information gathered from Cookies to authenticate your logins, determine whether you are logged in or not, to allow you to set personal preferences when using the Website, and to make it so you don't have to reenter the same information when you visit the Website several times within a short timeframe.	Information you provide to us; Transaction and Payment Information; Device/Internet Connection Information; Internet Activity Information; Geolocation Information
    To Communicate with You. We use your information to personalize communication with you, and to respond to your requests regarding your purchases and information on our products and services. We also use your information to notify you of updates to the Terms or this Privacy Policy.	Information you provide to us
    To Create Deidentified Aggregate Information. FA may combine your information with that of other users to create "Aggregate Information"— namely, statistical information about all users or a subset thereof. Aggregate Information is pseudonymized and deidentified. In other words, Aggregate Information cannot be used to identify, relate to, describe, be capable of being associated with, or be linked, directly or indirectly, to a particular consumer, including you. In turn, Aggregate Information may be used by FA for the Business and Commercial Purposes listed herein.	Information you provide to us; Content you make public; Device/Internet Connection Information; Internet Activity Information; Geolocation Information; Protected className Information
    Commercial Purposes. When FA uses your information for a "Commercial Purpose," it means such use is intended to advance FA' business interests, such as by inducing you to buy one of our services. The following are the Commercial Purposes for which we may use your information:
    Commercial Purpose	Types of Information
    To Advertise to You. We may use information gathered through Cookies and web beacons, including those placed by Third Parties, to deliver ads to you via the Website, and after you've left the Website, including advertising specific to your personal interests. The purpose of this practice, which is sometimes called "Personalized Ads," "retargeting," or "remarketing" is to deliver content and advertising that is of interest to you, and to avoid displaying irrelevant advertising to you.	Information you provide to us; Content you make public; Device/Internet Connection Information; Internet Activity Information; Geolocation Information
    To Advertise to Others. We may share your reviews, comments, and other content uploaded by you to advertise and market our Website and the Services, including by reposting your comments on the Website, in our advertising, or through our social media accounts.	Content you make public
    Scope and Legal Bases for Use FA only processes your information to the extent that is necessary to accomplish the above-stated Business and Commercial Purposes, which serves as our legitimate interest. If you reside in a location governed by the GDPR, then the following are FA' legal bases for the processing of your information: In so far as we have obtained consent for processing operations of information by the data subject, Art. 6(1) lit. a GDPR serves as the legal basis. For the processing of information necessary for the performance of a contract to which the data subject is a party, Art. 6(1) lit. b GDPR serves as legal basis. The same applies to such processing operations which are necessary for carrying out pre-contractual measures. In so far as the processing of information is required to comply with a legal obligation to which our FA is subject, Art. 6(1) lit. c GDPR serves as legal basis. In the event that processing of information may be necessary to protect the vital interests of the data subject or of another natural person, Art. 6(1) lit. d GDPR serves as legal basis. If processing is necessary for the purposes of the legitimate interests pursued by our FA or by a Third Party, except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject, processing operations are based on Art 6 (1) lit. f GDPR</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">5. How do we share your information?</h3>
 <p>FA may share your information with Third Parties for the following purposes:
    Business Purposes. When FA shares your information for a Business Purpose, it means such use is reasonably necessary and proportionate to achieve an operational purpose of the FA. The following are the Business Purposes for which we may share your information:
    Third Parties	Business Purpose	Types of Information
    Other Users. The Website contains features that allow you to upload, post, transmit, display, perform or distribute content, including personal information about yourself. Once you have chosen to divulge information about yourself to another user, multiple users, or the public at large through the Website— including in a "members-only" forum, direct message or otherwise—such information can be copied, transmitted or displayed by the recipient(s) and is no longer within FA' ability to control.	To provide the Website and allow you and other users the opportunity to communicate via a forum.	Content you make public
    Forum Administrators and Moderators. When you join, access, or post on a forum, information may be shared with other members that assist in running the forum, such as administrators or moderators.	To provide the Website and allow you and other users the opportunity to communicate via a forum.	Information you provide to us; Content you make public; Device/Internet Connection Information; Geolocation Information;
    Service Providers. These Third Parties provide services to FA that allow FA to operate the Website, provide services to customers, communicate with customers, and so forth. Examples include payment processors, email fulfillment providers, customer management services, and so forth.	For Security; To Fulfill Your Orders; to Improve the Website, to Personalize Your User Experience; and to Create Aggregate Information. See Section 4 for more information on these Business Purposes.	Information you provide to us; Content you make public; Transaction and Payment Information; Device/Internet Connection Information; Internet Activity Information; Geolocation Information; Protected className Information
    Our Affiliated Entities. Affiliated entities are different than Third Parties in that they are businesses that are directly related to us and have common ownership with us. We may disclose, transfer, and sell your information to our affiliated entities, in which event, your information shall be treated by the affiliated companies in accordance with this Privacy Policy. Should Company be subject to an acquisition, merger, or other change of control or business entity status, we reserve the right to transfer or assign your information as part of that acquisition, merger or change of control.	For Security; To Fulfill Your Orders; to Improve the Website, to Personalize Your User Experience; and to Create Aggregate Information. See Section 4 for more information on these Business Purposes.	Information you provide to us; Content you make public; Transaction and Payment Information; Device/Internet Connection Information; Internet Activity Information; Geolocation Information; Protected className Information
    Government Officials and Private Parties Pursuant to Valid Legal Process. We may disclose your information in response to subpoenas, court orders, and other legal processes. In very rare circumstances, we may disclose personal information when we believe it is necessary in order to prevent illegal, fraudulent, or injurious actions that may cause harm to individuals.	To comply with FA' legal obligations and to prevent illegal, fraudulent, or injurious actions that may cause harm to individuals.	Information you provide to us; Content you make public; Transaction and Payment Information; Device/Internet Connection Information; Internet Activity Information; Geolocation Information; Protected className Information
    Commercial Purposes. When FA shares your information for a "Commercial Purpose," it means such disclosure is intended to advance FA' business interests, such as by advertising our products or services. The following are the Commercial Purposes for which we may share your information with Third Parties:
    Commercial Purpose	Types of Information
    Advertising Partners. We may disclose your personal information as needed to our Third-Party advertising partners.	To Advertise to You, including through Personalized Ads; to Advertise to Others. See Section 4 for more information on these Commercial Purposes.	Information you provide to us; Content you make public; Device/Internet Connection Information; Internet Activity Information; Geolocation Information
    Forum Indexers. As explained more fully in Section 6, FA allows third-party Effyis, Inc. dba: BoardReader.com to index the public forums on the Website in exchange for a fee.	To promote the Website and create ease of access of Website content; to earn revenue.	Content you make public
    Other Consumers. We may share your reviews, comments, and other content uploaded by you to advertise and market our Website and the Services, including by reposting your reviews on the Website, in our advertising, or through our social media accounts.	To Advertise to Others. See Section 4 for more information on this Commercial Purpose.	Content you make public</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">6. Do we sell your information to others?</h3>
 <p>No.</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">7. How do we protect your information?</h3>
 <p>FA has implemented and maintains reasonable security procedures and practices to protect against the unauthorized access, use or disclosure of your information. Among other things, we:
    Host our servers with in secure data center facilities;
    Use services to block bots, malicious traffic, and secure our login systems with HTTPS/SSL;
    Store passwords in a secure format, not plain text; and
    Use firewalls to provide further security to our systems.
    However, no system can be completely secure. Therefore, although we take steps to secure your information, we cannot promise, and you should not expect, that your personal and commercial information, or other communications, will always remain secure. The safety and security of your information also depends on you. Never share your password with anyone else and notify us as soon as possible if you believe your security has been breached.</p>
    <h3 className="text-2xl font-bold mb-2 mt-2">8. How long do we keep your information?</h3>
 <p>FA will retain your information for the length of time necessary to fulfill the Business Purposes and Commercial Purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law or valid court order. If you request deletion of your information pursuant to Section 10, your request will be processed according to the timeframes indicated therein and/or pursuant to any applicable legislation.</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">9. Do we transfer your information to a different country?</h3>
 <p>If you are visiting the Website from a location outside Singapore, your connection will be through and to servers located in Singapore, and all information you provide will be processed and securely maintained in our web servers and internal systems located within Singapore. By using the Website, you authorize and specifically consent to the transfer of personal data to Singapore and its storage and use as specified above when you provide such information to us.</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">10. What are your rights when it comes to accessing, correcting, or deleting your information, and how can you exercise them?</h3>
 <p>You may access all information we've collected and retained about you for purposes of correcting, amending, downloading, or deleting such information. Access can be obtained by logging into your account, making a Privacy Request, or contacting us at privacy@filipinoart.ph. To protect your privacy and security, we may take reasonable steps to help verify your identity before granting access, making corrections, providing you with information, or deleting information. Such verification will include requiring you to login to your or, in the event you have forgotten your login credentials, completing the reset process so that you may log into your account.
    Access and Correction The easiest way to manage the content and information you share by logging into your account. You can also download information associated with your FA by visiting your Settings page. In the alternative, you may make a Privacy Request, or contact us at privacy@filipinoart.ph.
    Right to Request Disclosure You have the right to request that FA disclose the following to you:
    The categories of personal information we have collected about you;
    The categories of sources from which the personal information is collected;
    The business or commercial purpose for collecting or selling personal information;
    The specific pieces of personal information we have collected about you.
    To request such a disclosure, please make a Privacy Request, or contact us at privacy@filipinoart.ph.
    Right to Request Deletion You can have your FA information deleted from the website by sending us an email. You also have the right to request that FA delete any personal information about you which we have collected from you. To make either such a request, please make a Privacy Request, or contact us at privacy@filipinoart.ph and use the email subject: "REMOVAL personal information".</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">11. How can you receive and opt-out from marketing communications?</h3>
 <p>By providing your email address to FA through the Website or an email initiated by you, you consent to receive emails from us, including information concerning your and advertising messages. Depending upon your location, we may obtain additional consent from you via a checkbox disclosure or an email requesting confirmation before you can receive such information. Providing consent to promotional emails is NOT a condition of purchasing any goods or services from FA. You can unsubscribe to advertising emails at any time by clicking the unsubscribe link within the email. Please note that, even if you unsubscribe from advertising emails, we will still send you any necessary, non-promotional emails about your purchase, , or updates to our Privacy Policy and Terms of Service.</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">12. Do we respond to Do Not Track (DNT) Signals?</h3>
 <p>DNT is a feature offered by some browsers which, when enabled, sends a signal to websites to request that your browsing is not tracked. FA does not currently respond to DNT requests.</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">13. How will you know when we change the Privacy Policy?</h3>
 <p>Each time you use the Website, the then-current version of this Privacy Policy will apply. Although most changes are likely to be minor, we reserve the right to modify this Privacy Policy by posting such modification on this page; however, if changes are significant, we may provide a more prominent notice or email you. Depending upon your location, we may obtain additional consent from you via a checkbox disclosure, email, or personal message. Unless we receive your express consent, any revised Privacy Policy will apply only to information collected after the effective date of such revised Privacy Policy, and not to information collected under any earlier version.</p>
 <h3 className="text-2xl font-bold mb-2 mt-2">14. How can you contact us regarding this Privacy Policy?</h3>
 <p>You can contact us via email at privacy@filipinoart.ph. In this case, your information transmitted by email will be stored. If needed, your information will be relayed to our Third-Party partners to for the sole purpose of processing any request by you in the communication.</p>
    </div>
  )
}
